include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    invalid_annotation_target: ignore
    prefer_single_quotes: error
    require_trailing_commas: warning
    unused_element: ignore
    unused_element_parameter: ignore
    unused_local_variable: ignore
  plugins:
    - dart_code_metrics
  exclude:
    - "**/generated**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/main/logic/bridge_generated3.dart"
    - "**/*.gform.dart"

linter:
  rules:
    require_trailing_commas: true
    depend_on_referenced_packages: false
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors: true
    avoid_print: false # I work in debug mode, not production
    prefer_single_quotes: true
    overridden_fields: true
    library_private_types_in_public_api: false
    no_leading_underscores_for_library_prefixes: false

    avoid_relative_lib_imports: true
    always_use_package_imports: true

    avoid_empty_else: true
    always_put_required_named_parameters_first: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_null_for_void: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    constant_identifier_names: true
    directives_ordering: true
    no_leading_underscores_for_local_identifiers: true
    noop_primitive_operations: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_null_aware_method_calls: true
    prefer_spread_collections: true
    unnecessary_await_in_return: true
    use_named_constants: true
    sort_constructors_first: true
    always_declare_return_types: true
    collection_methods_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    avoid_init_to_null: true
    avoid_shadowing_type_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    curly_braces_in_flow_control_structures: true
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    avoid_renaming_method_parameters: false

dart_code_metrics:
  rules:
    - prefer-trailing-comma
    - no-equal-then-else
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-redundant-async
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - double-literal-format
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-correct-type-name
    - prefer-enums-by-name
    #    - prefer-moving-to-variable
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - member-ordering:
        order:
          - constructors
          - static-fields
          - final-fields
          - fields
        widgets-order:
          - constructor
          - static-fields
          - final-fields
          - fields
          - init-state-method
          - dispose-method
          - build-method
  metrics-exclude:
    - test/**
    - lib/core/l10n/generated/**
    - lib/main/logic/bridge_generated3.dart
    - lib/common/widgets/svg_icons.dart
  rules-exclude:
    - test/**
    - lib/main/logic/bridge_generated3.dart
    - lib/common/widgets/svg_icons.dart
